---
#- hosts: all

#  tasks:
    - name: Set timezone
      timezone:
        name: Asia/Yekaterinburg

    - name: Setup apt A
      copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} main contrib non-free
          deb http://security.debian.org/debian-security {{ ansible_distribution_release }}-security main contrib non-free
          deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-updates main contrib non-free
          deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-backports main contrib non-free
      when: ansible_distribution_major_version | int >= 11

    - name: Setup apt B
      copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} main contrib non-free
          deb http://security.debian.org/debian-security {{ ansible_distribution_release }}/updates main contrib non-free
          deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-updates main contrib non-free
          deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-backports main contrib non-free
      when: ansible_distribution_major_version | int < 11

    - name: Update and upgrade apt packages
      apt:
        upgrade: false
        update_cache: true
      tags:
      - apt-update

    - name: Install initial packages
      apt:
        name: [locales, sudo, mc, bash-completion]
        state: present
        install_recommends: false

    - name: Configure locales A
      locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Configure locales B
      locale_gen:
        name: ru_RU.UTF-8
        state: present

    - name: Config mc
      copy:
        dest: "/etc/mc/mc.ini"
        content: |
          [Midnight-Commander]
          use_internal_edit=true

          [Layout]
          message_visible=0
